/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ImpaPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var import_child_process = require("child_process");
var path = __toESM(require("path"));
var fs = __toESM(require("fs"));
var DEFAULT_TEMPLATES = [
  { id: "novel", label: "Novel", templatePath: "" },
  { id: "short", label: "Short", templatePath: "" },
  { id: "pitch", label: "Pitch", templatePath: "" },
  { id: "comic", label: "Comic", templatePath: "" }
];
var DEFAULT_SETTINGS = {
  templates: DEFAULT_TEMPLATES,
  exportDirectory: "",
  overwriteExisting: false,
  pandocPath: "pandoc"
};
function incrementVersion(filename) {
  const versionPattern = /^(.*?)(\d+)\.(\d+)(\.[^.]+)$/;
  const match = filename.match(versionPattern);
  if (!match) {
    const dotIdx = filename.lastIndexOf(".");
    if (dotIdx === -1)
      return filename + " 1.0";
    return filename.slice(0, dotIdx) + " 1.0" + filename.slice(dotIdx);
  }
  const prefix = match[1];
  const major = parseInt(match[2], 10);
  const minor = parseInt(match[3], 10);
  const ext = match[4];
  const newMinor = minor + 1;
  return `${prefix}${major}.${newMinor}${ext}`;
}
function resolveOutputPath(desiredPath) {
  if (!fs.existsSync(desiredPath))
    return desiredPath;
  const ext = path.extname(desiredPath);
  const base = desiredPath.slice(0, desiredPath.length - ext.length);
  let counter = 2;
  while (fs.existsSync(`${base} (${counter})${ext}`)) {
    counter++;
  }
  return `${base} (${counter})${ext}`;
}
var TemplatePicker = class extends import_obsidian.Modal {
  constructor(app, templates, onChoose) {
    super(app);
    this.templates = templates;
    this.onChoose = onChoose;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Impa \u2014 Choose Export Template" });
    contentEl.createEl("p", {
      text: "Select a Word template to use for this export.",
      cls: "impa-subtitle"
    });
    const validTemplates = this.templates.filter((t) => t.templatePath.trim() !== "");
    const allTemplates = this.templates;
    if (allTemplates.length === 0) {
      contentEl.createEl("p", { text: "No templates configured. Add them in Impa settings." });
      return;
    }
    const grid = contentEl.createDiv({ cls: "impa-template-grid" });
    for (const template of allTemplates) {
      const hasPath = template.templatePath.trim() !== "";
      const btn = grid.createEl("button", {
        text: template.label,
        cls: "impa-template-btn" + (hasPath ? "" : " impa-template-btn--disabled")
      });
      if (!hasPath) {
        btn.setAttribute("title", "No template path configured in settings");
        btn.setAttribute("disabled", "true");
      } else {
        btn.addEventListener("click", () => {
          this.close();
          this.onChoose(template);
        });
      }
    }
    const cancelRow = contentEl.createDiv({ cls: "impa-cancel-row" });
    cancelRow.createEl("button", { text: "Cancel", cls: "impa-cancel-btn" }).addEventListener("click", () => this.close());
  }
  onClose() {
    this.contentEl.empty();
  }
};
var ImpaSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Impa Settings" });
    new import_obsidian.Setting(containerEl).setName("Pandoc path").setDesc('Full path to your pandoc binary, or just "pandoc" if it is on your PATH.').addText((text) => text.setPlaceholder("pandoc").setValue(this.plugin.settings.pandocPath).onChange(async (value) => {
      this.plugin.settings.pandocPath = value.trim() || "pandoc";
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Default export directory").setDesc("Absolute path to the folder where exported .docx files are saved. Leave blank to save next to the source note.").addText((text) => text.setPlaceholder("/home/you/Documents/Exports").setValue(this.plugin.settings.exportDirectory).onChange(async (value) => {
      this.plugin.settings.exportDirectory = value.trim();
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Overwrite existing files").setDesc("If a file with the same name already exists in the export directory, overwrite it. When disabled, a unique suffix is added instead.").addToggle((toggle) => toggle.setValue(this.plugin.settings.overwriteExisting).onChange(async (value) => {
      this.plugin.settings.overwriteExisting = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Export Templates" });
    containerEl.createEl("p", {
      text: "Set the absolute path to each .docx reference template file. Pandoc uses these for formatting.",
      cls: "setting-item-description"
    });
    for (let i = 0; i < this.plugin.settings.templates.length; i++) {
      const tmpl = this.plugin.settings.templates[i];
      new import_obsidian.Setting(containerEl).setName(`${tmpl.label} template`).setDesc(`Absolute path to the ${tmpl.label} .docx reference template`).addText((text) => text.setPlaceholder("/home/you/Templates/novel-template.docx").setValue(tmpl.templatePath).onChange(async (value) => {
        this.plugin.settings.templates[i].templatePath = value.trim();
        await this.plugin.saveSettings();
      }));
    }
  }
};
var ImpaPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "impa-increment-version",
      name: "Increment note version",
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        if (!file)
          return false;
        if (checking)
          return true;
        this.incrementNoteVersion(file);
      }
    });
    this.addCommand({
      id: "impa-export-docx",
      name: "Export to DOCX via Pandoc",
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        if (!file)
          return false;
        if (checking)
          return true;
        this.promptExportDocx(file);
      }
    });
    this.addSettingTab(new ImpaSettingTab(this.app, this));
  }
  onunload() {
  }
  async loadSettings() {
    const saved = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, saved);
    if (!this.settings.templates || this.settings.templates.length === 0) {
      this.settings.templates = DEFAULT_TEMPLATES.map((t) => ({ ...t }));
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  // ── Version increment ────────────────────────────────────────────────────
  async incrementNoteVersion(file) {
    var _a, _b;
    const folder = (_b = (_a = file.parent) == null ? void 0 : _a.path) != null ? _b : "";
    const newName = incrementVersion(file.name);
    const newPath = folder ? `${folder}/${newName}` : newName;
    if (this.app.vault.getAbstractFileByPath(newPath)) {
      new import_obsidian.Notice(`\u26A0\uFE0F  Impa: "${newName}" already exists in this folder.`);
      return;
    }
    try {
      const content = await this.app.vault.read(file);
      await this.app.vault.create(newPath, content);
      const newFile = this.app.vault.getAbstractFileByPath(newPath);
      if (newFile instanceof import_obsidian.TFile) {
        await this.app.workspace.getLeaf(false).openFile(newFile);
      }
      new import_obsidian.Notice(`\u2705  Impa: Created "${newName}"`);
    } catch (err) {
      console.error("Impa version increment error:", err);
      new import_obsidian.Notice(`\u274C  Impa: Failed to create "${newName}". See console for details.`);
    }
  }
  // ── Pandoc export ────────────────────────────────────────────────────────
  promptExportDocx(file) {
    const configured = this.settings.templates.filter((t) => t.templatePath.trim() !== "");
    if (configured.length === 0) {
      new import_obsidian.Notice("\u26A0\uFE0F  Impa: No templates configured. Add template paths in Impa settings.");
      return;
    }
    new TemplatePicker(this.app, this.settings.templates, (template) => {
      this.runPandocExport(file, template);
    }).open();
  }
  async runPandocExport(file, template) {
    const vaultRoot = this.app.vault.adapter.basePath;
    const sourcePath = path.join(vaultRoot, file.path);
    const baseName = file.basename + ".docx";
    let exportDir = this.settings.exportDirectory.trim();
    if (!exportDir) {
      exportDir = path.dirname(sourcePath);
    }
    if (!fs.existsSync(exportDir)) {
      try {
        fs.mkdirSync(exportDir, { recursive: true });
      } catch (err) {
        new import_obsidian.Notice(`\u274C  Impa: Could not create export directory: ${exportDir}`);
        return;
      }
    }
    let outputPath = path.join(exportDir, baseName);
    if (!this.settings.overwriteExisting) {
      outputPath = resolveOutputPath(outputPath);
    }
    const pandoc = this.settings.pandocPath || "pandoc";
    const templateArg = `--reference-doc="${template.templatePath}"`;
    const command = `"${pandoc}" "${sourcePath}" -o "${outputPath}" ${templateArg}`;
    new import_obsidian.Notice(`\u23F3  Impa: Exporting "${file.name}" as ${template.label}\u2026`);
    (0, import_child_process.exec)(command, { cwd: path.dirname(sourcePath) }, (error, stdout, stderr) => {
      if (error) {
        console.error("Impa pandoc error:", error);
        console.error("stderr:", stderr);
        new import_obsidian.Notice(`\u274C  Impa: Export failed.
${stderr || error.message}`);
        return;
      }
      const outFile = path.basename(outputPath);
      new import_obsidian.Notice(`\u2705  Impa: Exported "${outFile}" using ${template.label} template.`);
    });
  }
};
