/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ImpaPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var import_child_process = require("child_process");
var path = __toESM(require("path"));
var fs = __toESM(require("fs"));
var DEFAULT_TEMPLATES = [
  { id: "novel", label: "Novel", templatePath: "" },
  { id: "short", label: "Short", templatePath: "" },
  { id: "pitch", label: "Pitch", templatePath: "" },
  { id: "comic", label: "Comic", templatePath: "" }
];
var DEFAULT_SETTINGS = {
  templates: DEFAULT_TEMPLATES,
  exportDirectory: "",
  overwriteExisting: false,
  pandocPath: "pandoc"
};
var VaultFileSuggest = class extends import_obsidian.AbstractInputSuggest {
  constructor(app, inputEl, onSelect) {
    super(app, inputEl);
    this.inputEl = inputEl;
    this.onSelect = onSelect;
    this.vaultRoot = app.vault.adapter.basePath;
  }
  getSuggestions(query) {
    const q = query.toLowerCase().replace(/\\/g, "/");
    return this.findDocxFiles(this.vaultRoot, this.vaultRoot).filter((f) => f.toLowerCase().replace(/\\/g, "/").includes(q)).slice(0, 20);
  }
  renderSuggestion(vaultRelPath, el) {
    var _a;
    const parts = vaultRelPath.split("/");
    const fileName = (_a = parts.pop()) != null ? _a : vaultRelPath;
    const folder = parts.join("/");
    el.createEl("div", { text: fileName, cls: "impa-suggest-filename" });
    if (folder)
      el.createEl("small", { text: folder, cls: "impa-suggest-folder" });
  }
  // Called by Obsidian when the user clicks or keyboards-selects a suggestion.
  selectSuggestion(vaultRelPath, _evt) {
    this.inputEl.value = vaultRelPath;
    this.onSelect(vaultRelPath);
    this.close();
  }
  findDocxFiles(dir, root) {
    const results = [];
    try {
      for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
        if (entry.name.startsWith(".") || entry.name === "node_modules")
          continue;
        const full = path.join(dir, entry.name);
        if (entry.isDirectory()) {
          results.push(...this.findDocxFiles(full, root));
        } else if (entry.isFile() && entry.name.toLowerCase().endsWith(".docx")) {
          results.push(path.relative(root, full).replace(/\\/g, "/"));
        }
      }
    } catch (_) {
    }
    return results;
  }
};
function incrementVersion(filename) {
  const m = filename.match(/^(.*?)(\d+)\.(\d+)(\.[^.]+)$/);
  if (!m) {
    const dot = filename.lastIndexOf(".");
    return dot === -1 ? filename + " 1.0" : filename.slice(0, dot) + " 1.0" + filename.slice(dot);
  }
  return `${m[1]}${parseInt(m[2], 10)}.${parseInt(m[3], 10) + 1}${m[4]}`;
}
function resolveOutputPath(p) {
  if (!fs.existsSync(p))
    return p;
  const ext = path.extname(p);
  const base = p.slice(0, p.length - ext.length);
  let n = 2;
  while (fs.existsSync(`${base} (${n})${ext}`))
    n++;
  return `${base} (${n})${ext}`;
}
function generateId() {
  return "tmpl_" + Math.random().toString(36).slice(2, 9);
}
var TemplatePicker = class extends import_obsidian.Modal {
  constructor(app, templates, onChoose) {
    super(app);
    this.templates = templates;
    this.onChoose = onChoose;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Impa \u2014 Choose Export Template" });
    contentEl.createEl("p", { text: "Select a Word template to use for this export.", cls: "impa-subtitle" });
    if (this.templates.length === 0) {
      contentEl.createEl("p", { text: "No templates configured. Add them in Impa settings." });
      return;
    }
    const grid = contentEl.createDiv({ cls: "impa-template-grid" });
    for (const tmpl of this.templates) {
      const hasPath = tmpl.templatePath.trim() !== "";
      const btn = grid.createEl("button", {
        text: tmpl.label,
        cls: "impa-template-btn" + (hasPath ? "" : " impa-template-btn--disabled")
      });
      if (!hasPath) {
        btn.setAttribute("title", "No template file configured in settings");
        btn.setAttribute("disabled", "true");
      } else {
        btn.addEventListener("click", () => {
          this.close();
          this.onChoose(tmpl);
        });
      }
    }
    contentEl.createDiv({ cls: "impa-cancel-row" }).createEl("button", { text: "Cancel", cls: "impa-cancel-btn" }).addEventListener("click", () => this.close());
  }
  onClose() {
    this.contentEl.empty();
  }
};
var ImpaSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
    this.suggests = [];
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    this.suggests.forEach((s) => s.close());
    this.suggests = [];
    const quote = containerEl.createEl("blockquote", { cls: "impa-hero-quote" });
    quote.createEl("p").innerHTML = `"Princess, it's dangerous to go alone! Take me!" \u2014 Impa, <em>Hyrule Warriors</em>`;
    containerEl.createEl("h2", { text: "Impa Settings", cls: "impa-settings-header" });
    new import_obsidian.Setting(containerEl).setName("Pandoc path").setDesc('Full path to the pandoc binary, or just "pandoc" if it is on your PATH.').addText((t) => t.setPlaceholder("pandoc").setValue(this.plugin.settings.pandocPath).onChange(async (v) => {
      this.plugin.settings.pandocPath = v.trim() || "pandoc";
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Default export directory").setDesc("Absolute path to the folder where exported .docx files are saved. Leave blank to save next to the source note.").addText((t) => t.setPlaceholder("/home/you/Documents/Exports").setValue(this.plugin.settings.exportDirectory).onChange(async (v) => {
      this.plugin.settings.exportDirectory = v.trim();
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Overwrite existing files").setDesc("Overwrite a file with the same name in the export directory. When disabled, a unique suffix is added instead.").addToggle((t) => t.setValue(this.plugin.settings.overwriteExisting).onChange(async (v) => {
      this.plugin.settings.overwriteExisting = v;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Export Templates" });
    containerEl.createEl("p", {
      text: "Give each template a name, then type to search for matching .docx files inside your vault. Selecting a suggestion fills the path automatically. Use the trash icon to remove a template.",
      cls: "setting-item-description"
    });
    const header = containerEl.createDiv({ cls: "impa-template-header" });
    header.createEl("span", { text: "Name" });
    header.createEl("span", { text: "Template file (vault path)" });
    header.createEl("span", { text: "" });
    for (let i = 0; i < this.plugin.settings.templates.length; i++) {
      this.renderTemplateRow(containerEl, i);
    }
    new import_obsidian.Setting(containerEl).addButton((btn) => btn.setButtonText("+ Add template").setCta().onClick(async () => {
      this.plugin.settings.templates.push({
        id: generateId(),
        label: "New Template",
        templatePath: ""
      });
      await this.plugin.saveSettings();
      this.display();
    }));
  }
  renderTemplateRow(containerEl, i) {
    const tmpl = this.plugin.settings.templates[i];
    const row = containerEl.createDiv({ cls: "impa-template-row" });
    const nameWrap = row.createDiv({ cls: "impa-template-cell" });
    const nameInput = nameWrap.createEl("input", {
      type: "text",
      cls: "impa-name-input"
    });
    nameInput.placeholder = "Template name";
    nameInput.value = tmpl.label;
    nameInput.addEventListener("change", async () => {
      this.plugin.settings.templates[i].label = nameInput.value;
      await this.plugin.saveSettings();
    });
    const pathWrap = row.createDiv({ cls: "impa-template-cell impa-template-cell--wide" });
    const pathInput = pathWrap.createEl("input", {
      type: "text",
      cls: "impa-path-input"
    });
    pathInput.placeholder = "Templates/my-template.docx";
    pathInput.value = tmpl.templatePath;
    pathInput.addEventListener("input", async () => {
      this.plugin.settings.templates[i].templatePath = pathInput.value.trim();
      await this.plugin.saveSettings();
    });
    const suggest = new VaultFileSuggest(
      this.app,
      pathInput,
      async (selected) => {
        pathInput.value = selected;
        this.plugin.settings.templates[i].templatePath = selected;
        await this.plugin.saveSettings();
      }
    );
    this.suggests.push(suggest);
    const delWrap = row.createDiv({ cls: "impa-template-cell impa-template-cell--btn" });
    const delBtn = delWrap.createEl("button", {
      cls: "impa-delete-btn",
      attr: { "aria-label": "Remove template" }
    });
    delBtn.innerHTML = `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="3 6 5 6 21 6"/><path d="M19 6l-1 14H6L5 6"/><path d="M10 11v6"/><path d="M14 11v6"/><path d="M9 6V4h6v2"/></svg>`;
    delBtn.addEventListener("click", async () => {
      this.plugin.settings.templates.splice(i, 1);
      await this.plugin.saveSettings();
      this.display();
    });
  }
};
var ImpaPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "impa-increment-version",
      name: "Increment note version",
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        if (!file)
          return false;
        if (checking)
          return true;
        this.incrementNoteVersion(file);
      }
    });
    this.addCommand({
      id: "impa-export-docx",
      name: "Export to DOCX via Pandoc",
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        if (!file)
          return false;
        if (checking)
          return true;
        this.promptExportDocx(file);
      }
    });
    this.addSettingTab(new ImpaSettingTab(this.app, this));
  }
  onunload() {
  }
  async loadSettings() {
    const saved = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, saved);
    if (!this.settings.templates || this.settings.templates.length === 0) {
      this.settings.templates = DEFAULT_TEMPLATES.map((t) => ({ ...t }));
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  // ── Version increment ────────────────────────────────────────────────────
  async incrementNoteVersion(file) {
    var _a, _b;
    const folder = (_b = (_a = file.parent) == null ? void 0 : _a.path) != null ? _b : "";
    const newName = incrementVersion(file.name);
    const newPath = folder ? `${folder}/${newName}` : newName;
    if (this.app.vault.getAbstractFileByPath(newPath)) {
      new import_obsidian.Notice(`\u26A0\uFE0F  Impa: "${newName}" already exists in this folder.`);
      return;
    }
    try {
      const content = await this.app.vault.read(file);
      await this.app.vault.create(newPath, content);
      const newFile = this.app.vault.getAbstractFileByPath(newPath);
      if (newFile instanceof import_obsidian.TFile)
        await this.app.workspace.getLeaf(false).openFile(newFile);
      new import_obsidian.Notice(`\u2705  Impa: Created "${newName}"`);
    } catch (err) {
      console.error("Impa version increment error:", err);
      new import_obsidian.Notice(`\u274C  Impa: Failed to create "${newName}". See console for details.`);
    }
  }
  // ── Pandoc export ────────────────────────────────────────────────────────
  promptExportDocx(file) {
    const configured = this.settings.templates.filter((t) => t.templatePath.trim() !== "");
    if (configured.length === 0) {
      new import_obsidian.Notice("\u26A0\uFE0F  Impa: No templates configured. Add template paths in Impa settings.");
      return;
    }
    new TemplatePicker(this.app, this.settings.templates, (tmpl) => this.runPandocExport(file, tmpl)).open();
  }
  async runPandocExport(file, template) {
    const vaultRoot = this.app.vault.adapter.basePath;
    const sourcePath = path.join(vaultRoot, file.path);
    const templateAbsPath = path.join(vaultRoot, template.templatePath);
    if (!fs.existsSync(templateAbsPath)) {
      new import_obsidian.Notice(`\u274C  Impa: Template file not found:
${template.templatePath}`);
      return;
    }
    const baseName = file.basename + ".docx";
    let exportDir = this.settings.exportDirectory.trim() || path.dirname(sourcePath);
    if (!fs.existsSync(exportDir)) {
      try {
        fs.mkdirSync(exportDir, { recursive: true });
      } catch (e) {
        new import_obsidian.Notice(`\u274C  Impa: Could not create export directory: ${exportDir}`);
        return;
      }
    }
    let outputPath = path.join(exportDir, baseName);
    if (!this.settings.overwriteExisting)
      outputPath = resolveOutputPath(outputPath);
    const pandoc = this.settings.pandocPath || "pandoc";
    const command = `"${pandoc}" "${sourcePath}" -o "${outputPath}" --reference-doc="${templateAbsPath}"`;
    new import_obsidian.Notice(`\u23F3  Impa: Exporting "${file.name}" as ${template.label}\u2026`);
    (0, import_child_process.exec)(command, { cwd: path.dirname(sourcePath) }, (error, _stdout, stderr) => {
      if (error) {
        console.error("Impa pandoc error:", error, stderr);
        new import_obsidian.Notice(`\u274C  Impa: Export failed.
${stderr || error.message}`);
        return;
      }
      new import_obsidian.Notice(`\u2705  Impa: Exported "${path.basename(outputPath)}" using ${template.label} template.`);
    });
  }
};
